<Project>

    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <Company>MASS4</Company>
        <Product>Gaya</Product>
        <Authors>Bruno Massa</Authors>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageProjectUrl>https://turian.mass4.org</PackageProjectUrl>
        <RepositoryUrl>https://github.com/MASS4ORG/Turian.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>gaya plugin platform workbench docking guinevere desktop</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" Visible="false" />
    </ItemGroup>

</Project>
