<Project>
    <!-- Internal paths -->
    <PropertyGroup>
        <SolutionDir Condition="'$(SolutionDir)' == ''">$(MSBuildThisFileDirectory)</SolutionDir>
        <UseFileScopedNamespaces>true</UseFileScopedNamespaces>
    </PropertyGroup>

    <!-- `Directory.Build.local.props` points to local project -->
    <Import Project="$(MSBuildThisFileDirectory)Directory.Build.local.props"
            Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.local.props')"/>

    <!-- External libraries included in every project -->
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="JetBrains.Annotations"/>
    </ItemGroup>
</Project>
