global using System;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Numerics;
global using System.Reflection;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Xml;
global using System.Xml.Linq;
global using Guinevere;
global using Microsoft.Extensions.Logging;
global using Silk.NET.Vulkan;
global using SkiaSharp;
global using Turian.Engine.Core;
global using GuiColor = Guinevere.Color;
global using SilkKey = Silk.NET.Input.Key;
global using SilkMouseButton = Silk.NET.Input.MouseButton;
