global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Globalization;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Text.RegularExpressions;
global using Gaya.Sdk;
global using Guinevere;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using SkiaSharp;
global using Turian;
global using Turian.Editor.Core;
global using Turian.Engine.Core;
global using Turian.Engine.UI;
global using GuiColor = Guinevere.Color;
global using SilkKey = Silk.NET.Input.Key;
global using SilkMouseButton = Silk.NET.Input.MouseButton;
