/// glTF/GLB and FBX node-hierarchy import: generates `"mesh:{d}"` sub-assets
/// (one per source mesh) and `"hierarchy"` sub-assets (prefab-shaped node tree
/// with mesh_renderer components). `generate` dispatches to `GltfLoader` or
/// `FbxLoader` by extension; the cooking logic is comptime-generic over both.
const std = @import("std");
const engine = @import("engine");
const Guid = @import("guid").Guid;
const SubAsset = @import("../types/MetaFile.zig").SubAsset;
const scene_io = @import("../project/SceneIo.zig");
const model_derived_assets = @import("ModelDerivedAssets.zig");

const GltfLoader = engine.assets.GltfLoader;
const FbxLoader = engine.assets.FbxLoader;
const SceneNode = engine.SceneNode;

fn asciiIeql(a: []const u8, b: []const u8) bool {
    return std.ascii.eqlIgnoreCase(a, b);
}

/// Cook source meshes + node graph into sub-assets. Materials must already
/// be generated by `ModelDerivedAssets.generate`. Best-effort: parse failures
/// leave `subs` untouched.
pub fn generate(
    io: std.Io,
    allocator: std.mem.Allocator,
    project_path: []const u8,
    asset_path: []const u8,
    prev: []const SubAsset,
    materials_so_far: []const SubAsset,
    subs: *std.ArrayList(SubAsset),
) void {
    const ext = std.fs.path.extension(asset_path);
    if (asciiIeql(ext, ".gltf") or asciiIeql(ext, ".glb")) {
        generateFrom(GltfLoader, io, allocator, project_path, asset_path, prev, materials_so_far, subs);
    } else if (asciiIeql(ext, ".fbx")) {
        generateFrom(FbxLoader, io, allocator, project_path, asset_path, prev, materials_so_far, subs);
    }
}

fn generateFrom(
    comptime Loader: type,
    io: std.Io,
    allocator: std.mem.Allocator,
    project_path: []const u8,
    asset_path: []const u8,
    prev: []const SubAsset,
    materials_so_far: []const SubAsset,
    subs: *std.ArrayList(SubAsset),
) void {
    const arena = allocator;

    const groups = Loader.loadMeshes(arena, asset_path) catch return;
    var hier = Loader.loadHierarchy(arena, asset_path) catch return;
    defer hier.deinit();
    if (hier.nodes.len == 0) return;

    // Mesh GUIDs, indexed the same way as `groups`/`hier.nodes[i].mesh_index`.
    const mesh_guids = arena.alloc(Guid, groups.len) catch return;
    for (groups, 0..) |g, i| {
        var key_buf: [32]u8 = undefined;
        const key = std.fmt.bufPrint(&key_buf, "mesh:{d}", .{i}) catch continue;
        const guid = model_derived_assets.reuseOrNewGuid(prev, key, io);
        mesh_guids[i] = guid;

        const bytes = g.mesh.encode(arena) catch continue;
        if (!model_derived_assets.writeBytesArtifact(io, project_path, guid, .model, bytes)) continue;

        const name = if (g.name.len > 0)
            std.fmt.allocPrint(arena, "{s}.mesh", .{g.name}) catch "mesh.mesh"
        else
            std.fmt.allocPrint(arena, "mesh_{d}.mesh", .{i}) catch "mesh.mesh";
        subs.append(arena, .{ .guid = guid, .asset_type = .model, .key = arena.dupe(u8, key) catch key, .name = name }) catch {};
    }

    const scene_nodes = buildSceneNodes(arena, hier.nodes, groups, mesh_guids, materials_so_far) orelse return;
    const bytes = scene_io.serializeScene(arena, scene_nodes, scene_nodes.len) orelse return;

    const guid = model_derived_assets.reuseOrNewGuid(prev, "hierarchy", io);
    if (!model_derived_assets.writeBytesArtifact(io, project_path, guid, .scene, bytes)) return;

    const base = std.fs.path.stem(asset_path);
    const name = std.fmt.allocPrint(arena, "{s}.prefab", .{base}) catch "hierarchy.prefab";
    subs.append(arena, .{ .guid = guid, .asset_type = .scene, .key = "hierarchy", .name = name }) catch {};
}

/// Builds one `SceneNode` per source node, reordered so parents always
/// precede children (neither loader's node array guarantees this, but the
/// engine's scene/prefab code — e.g. `Prefab.collectSubtree` — assumes it).
/// `nodes`/`groups` are `anytype`: `GltfLoader`/`FbxLoader` expose
/// structurally identical but nominally distinct types for these.
fn buildSceneNodes(
    arena: std.mem.Allocator,
    nodes: anytype,
    groups: anytype,
    mesh_guids: []const Guid,
    materials_so_far: []const SubAsset,
) ?[]SceneNode {
    const order = topoOrder(arena, nodes) catch return null;
    const new_index = arena.alloc(i32, nodes.len) catch return null;
    for (order, 0..) |old_i, new_i| new_index[old_i] = @intCast(new_i);

    const scene_nodes = arena.alloc(SceneNode, nodes.len) catch return null;
    for (order, 0..) |old_i, new_i| {
        const n = nodes[old_i];
        var node = SceneNode{};
        node.setName(n.name);
        node.parent = if (n.parent < 0) -1 else new_index[@intCast(n.parent)];
        node.transform = .{
            .position = .{ .x = n.position[0], .y = n.position[1], .z = n.position[2] },
            .rotation = .{ .x = n.rotation_euler_deg[0], .y = n.rotation_euler_deg[1], .z = n.rotation_euler_deg[2] },
            .scale = .{ .x = n.scale[0], .y = n.scale[1], .z = n.scale[2] },
        };
        if (n.mesh_index >= 0 and @as(usize, @intCast(n.mesh_index)) < groups.len) {
            attachMeshRenderer(&node, n.mesh_index, groups, mesh_guids, materials_so_far);
        }
        scene_nodes[new_i] = node;
    }
    return scene_nodes;
}

fn attachMeshRenderer(
    node: *SceneNode,
    mesh_index: i32,
    groups: anytype,
    mesh_guids: []const Guid,
    materials_so_far: []const SubAsset,
) void {
    const mi: usize = @intCast(mesh_index);
    var comp = engine.MeshRendererComponent{};
    var guid_buf: [36]u8 = undefined;
    comp.mesh.set(mesh_guids[mi].toString(&guid_buf));

    const submeshes = groups[mi].mesh.submeshes;
    var max_slot: i32 = -1;
    for (submeshes) |sm| {
        if (sm.material_slot > max_slot) max_slot = sm.material_slot;
    }
    if (max_slot >= 0) {
        const n = @min(@as(usize, @intCast(max_slot + 1)), engine.MeshRendererComponent.MAX_MATERIALS);
        for (0..n) |slot| {
            var key_buf: [32]u8 = undefined;
            const key = std.fmt.bufPrint(&key_buf, "material:{d}", .{slot}) catch continue;
            for (materials_so_far) |s| {
                if (s.asset_type != .material or !std.mem.eql(u8, s.key, key)) continue;
                var mat_guid_buf: [36]u8 = undefined;
                comp.materials[slot].set(s.guid.toString(&mat_guid_buf));
                break;
            }
        }
        comp.material_count = @intCast(n);
    }
    _ = node.addComponent(.{ .mesh_renderer = comp });
}

/// Kahn's-algorithm topological order (parents before children). Any node
/// left over after the graph is exhausted (a cycle — shouldn't occur in a
/// valid source file) is appended in its original order rather than dropped.
fn topoOrder(arena: std.mem.Allocator, nodes: anytype) ![]usize {
    const emitted_at = try arena.alloc(i32, nodes.len);
    @memset(emitted_at, -1);
    const order = try arena.alloc(usize, nodes.len);

    var count: usize = 0;
    var progress = true;
    while (count < nodes.len and progress) {
        progress = false;
        for (nodes, 0..) |n, i| {
            if (emitted_at[i] != -1) continue;
            const ready = n.parent < 0 or emitted_at[@intCast(n.parent)] != -1;
            if (!ready) continue;
            emitted_at[i] = @intCast(count);
            order[count] = i;
            count += 1;
            progress = true;
        }
    }
    if (count < nodes.len) {
        for (0..nodes.len) |i| {
            if (emitted_at[i] != -1) continue;
            emitted_at[i] = @intCast(count);
            order[count] = i;
            count += 1;
        }
    }
    return order;
}
