/// glTF/GLB node-hierarchy import (one-to-many, like `ModelDerivedAssets.zig`):
///   * one `.model`-typed `"mesh:{d}"` sub-asset per glTF *mesh* (its own
///     submesh table, scoped to that mesh's primitives — unlike the source
///     asset's own cooked artifact, which flattens every primitive in the
///     file into one combined mesh),
///   * one `.scene`-typed `"hierarchy"` sub-asset: a prefab-shaped node tree
///     (`SceneIo.serializeScene`) with a `mesh_renderer` component on every
///     mesh-bearing node, materials resolved positionally against the
///     `"material:{d}"` sub-assets `ModelDerivedAssets.generate` already
///     produced. Registering it as `asset_type = .scene` means dragging it
///     into a scene reuses the existing prefab-instantiate path with no new
///     instantiation logic (see `Prefab.zig`/`SceneViewport.zig`).
/// glTF/GLB only — FBX hierarchy is out of scope (separate issue).
const std = @import("std");
const engine = @import("engine");
const Guid = @import("guid").Guid;
const SubAsset = @import("../types/MetaFile.zig").SubAsset;
const scene_io = @import("../project/SceneIo.zig");
const model_derived_assets = @import("ModelDerivedAssets.zig");

const GltfLoader = engine.assets.GltfLoader;
const SceneNode = engine.SceneNode;

/// Cook every glTF mesh + the node graph of `asset_path` into `"mesh:{d}"`
/// and `"hierarchy"` sub-assets, appended to `subs`. `materials_so_far` is
/// the sub-asset list built so far this import (materials must already be
/// generated by `ModelDerivedAssets.generate` before this runs). Best-effort:
/// parse failures leave `subs` untouched rather than failing the import.
pub fn generate(
    io: std.Io,
    allocator: std.mem.Allocator,
    project_path: []const u8,
    asset_path: []const u8,
    prev: []const SubAsset,
    materials_so_far: []const SubAsset,
    subs: *std.ArrayList(SubAsset),
) void {
    const arena = allocator;

    const groups = GltfLoader.loadMeshes(arena, asset_path) catch return;
    var hier = GltfLoader.loadHierarchy(arena, asset_path) catch return;
    defer hier.deinit();
    if (hier.nodes.len == 0) return;

    // Mesh GUIDs, indexed the same way as `groups`/`hier.nodes[i].mesh_index`.
    const mesh_guids = arena.alloc(Guid, groups.len) catch return;
    for (groups, 0..) |g, i| {
        var key_buf: [32]u8 = undefined;
        const key = std.fmt.bufPrint(&key_buf, "mesh:{d}", .{i}) catch continue;
        const guid = model_derived_assets.reuseOrNewGuid(prev, key, io);
        mesh_guids[i] = guid;

        const bytes = g.mesh.encode(arena) catch continue;
        if (!model_derived_assets.writeBytesArtifact(io, project_path, guid, .model, bytes)) continue;

        const name = if (g.name.len > 0)
            std.fmt.allocPrint(arena, "{s}.mesh", .{g.name}) catch "mesh.mesh"
        else
            std.fmt.allocPrint(arena, "mesh_{d}.mesh", .{i}) catch "mesh.mesh";
        subs.append(arena, .{ .guid = guid, .asset_type = .model, .key = arena.dupe(u8, key) catch key, .name = name }) catch {};
    }

    const scene_nodes = buildSceneNodes(arena, hier.nodes, groups, mesh_guids, materials_so_far) orelse return;
    const bytes = scene_io.serializeScene(arena, scene_nodes, scene_nodes.len) orelse return;

    const guid = model_derived_assets.reuseOrNewGuid(prev, "hierarchy", io);
    if (!model_derived_assets.writeBytesArtifact(io, project_path, guid, .scene, bytes)) return;

    const base = std.fs.path.stem(asset_path);
    const name = std.fmt.allocPrint(arena, "{s}.prefab", .{base}) catch "hierarchy.prefab";
    subs.append(arena, .{ .guid = guid, .asset_type = .scene, .key = "hierarchy", .name = name }) catch {};
}

/// Builds one `SceneNode` per glTF node, reordered so parents always precede
/// children (glTF's node array has no such ordering guarantee, but the
/// engine's scene/prefab code — e.g. `Prefab.collectSubtree` — assumes it).
fn buildSceneNodes(
    arena: std.mem.Allocator,
    gltf_nodes: []const GltfLoader.GltfNode,
    groups: []const GltfLoader.MeshGroup,
    mesh_guids: []const Guid,
    materials_so_far: []const SubAsset,
) ?[]SceneNode {
    const order = topoOrder(arena, gltf_nodes) catch return null;
    const new_index = arena.alloc(i32, gltf_nodes.len) catch return null;
    for (order, 0..) |old_i, new_i| new_index[old_i] = @intCast(new_i);

    const scene_nodes = arena.alloc(SceneNode, gltf_nodes.len) catch return null;
    for (order, 0..) |old_i, new_i| {
        const gn = gltf_nodes[old_i];
        var node = SceneNode{};
        node.setName(gn.name);
        node.parent = if (gn.parent < 0) -1 else new_index[@intCast(gn.parent)];
        node.transform = .{
            .position = .{ .x = gn.position[0], .y = gn.position[1], .z = gn.position[2] },
            .rotation = .{ .x = gn.rotation_euler_deg[0], .y = gn.rotation_euler_deg[1], .z = gn.rotation_euler_deg[2] },
            .scale = .{ .x = gn.scale[0], .y = gn.scale[1], .z = gn.scale[2] },
        };
        if (gn.mesh_index >= 0 and @as(usize, @intCast(gn.mesh_index)) < groups.len) {
            attachMeshRenderer(&node, gn.mesh_index, groups, mesh_guids, materials_so_far);
        }
        scene_nodes[new_i] = node;
    }
    return scene_nodes;
}

fn attachMeshRenderer(
    node: *SceneNode,
    mesh_index: i32,
    groups: []const GltfLoader.MeshGroup,
    mesh_guids: []const Guid,
    materials_so_far: []const SubAsset,
) void {
    const mi: usize = @intCast(mesh_index);
    var comp = engine.MeshRendererComponent{};
    var guid_buf: [36]u8 = undefined;
    comp.mesh.set(mesh_guids[mi].toString(&guid_buf));

    const submeshes = groups[mi].mesh.submeshes;
    const n = @min(submeshes.len, engine.MeshRendererComponent.MAX_SUBMESH_MATERIALS);
    for (submeshes[0..n], 0..) |sm, si| {
        if (sm.material_slot < 0) continue;
        var key_buf: [32]u8 = undefined;
        const key = std.fmt.bufPrint(&key_buf, "material:{d}", .{sm.material_slot}) catch continue;
        for (materials_so_far) |s| {
            if (s.asset_type != .material or !std.mem.eql(u8, s.key, key)) continue;
            var mat_guid_buf: [36]u8 = undefined;
            comp.materials[si].set(s.guid.toString(&mat_guid_buf));
            break;
        }
    }
    comp.material_count = @intCast(n);
    _ = node.addComponent(.{ .mesh_renderer = comp });
}

/// Kahn's-algorithm topological order (parents before children). Any node
/// left over after the graph is exhausted (a cycle — shouldn't occur in a
/// valid glTF file) is appended in its original order rather than dropped.
fn topoOrder(arena: std.mem.Allocator, nodes: []const GltfLoader.GltfNode) ![]usize {
    const emitted_at = try arena.alloc(i32, nodes.len);
    @memset(emitted_at, -1);
    const order = try arena.alloc(usize, nodes.len);

    var count: usize = 0;
    var progress = true;
    while (count < nodes.len and progress) {
        progress = false;
        for (nodes, 0..) |n, i| {
            if (emitted_at[i] != -1) continue;
            const ready = n.parent < 0 or emitted_at[@intCast(n.parent)] != -1;
            if (!ready) continue;
            emitted_at[i] = @intCast(count);
            order[count] = i;
            count += 1;
            progress = true;
        }
    }
    if (count < nodes.len) {
        for (0..nodes.len) |i| {
            if (emitted_at[i] != -1) continue;
            emitted_at[i] = @intCast(count);
            order[count] = i;
            count += 1;
        }
    }
    return order;
}
