global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Globalization;
global using System.IO;
global using System.IO.Compression;
global using System.Linq;
global using System.Net.Http;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using Nuke.Common;
global using Nuke.Common.CI;
global using Nuke.Common.IO;
global using Nuke.Common.ProjectModel;
global using Nuke.Common.Tooling;
global using Nuke.Common.Tools.DotNet;
global using Nuke.Common.Tools.GitVersion;
global using Nuke.Common.Tools.ReportGenerator;
global using Nuke.Common.Utilities.Collections;
global using Serilog;
global using static Nuke.Common.Tools.DotNet.DotNetTasks;
global using static Nuke.Common.Tools.Git.GitTasks;
global using static Nuke.Common.Tools.ReportGenerator.ReportGeneratorTasks;
