global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Formats.Tar;
global using System.Globalization;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.Json.Serialization;
